package io.github.frenchiiifries.emb3r.ui

// Generated by android/tools/mark_to_kotlin.py from #logoMark in src/index.html.
// Do not edit by hand - change the desktop's mark and regenerate.

/** The seven tiers of the salamander, each a mix of the accent colour. */
enum class Tier { O, D, B, G, F1, F2, F3 }

object CoilMarkData {
    /** The canvas the paths are drawn on, in the SVG's own units. */
    const val VIEWBOX = 40f

    /** The body and the flame bases, which do not move. */
    val static: List<Pair<Tier, String>> = listOf(
        Tier.O to "M17 6h3v1h-3zM25 7h2v1h-2zM11 8h2v1h-2zM27 8h5v1h-5zM10 9h1v1h-1zM32 9h1v1h-1zM9 10h1v1h-1zM26 10h1v1h-1zM33 10h1v1h-1zM25 11h1v1h-1zM31 11h1v1h-1zM34 11h1v1h-1zM20 12h1v1h-1zM25 12h1v1h-1zM30 12h2v1h-2zM33 12h1v1h-1zM35 12h1v1h-1zM19 13h1v1h-1zM23 13h1v1h-1zM25 13h1v1h-1zM28 13h2v1h-2zM35 13h1v1h-1zM5 14h1v1h-1zM18 14h1v1h-1zM22 14h5v1h-5zM30 14h5v1h-5zM5 15h1v1h-1zM17 15h2v1h-2zM21 15h2v1h-2zM27 15h2v1h-2zM32 15h1v1h-1zM34 15h1v1h-1zM4 16h1v1h-1zM15 16h2v1h-2zM18 16h2v1h-2zM23 16h2v1h-2zM29 16h4v1h-4zM34 16h1v1h-1zM4 17h1v1h-1zM14 17h1v1h-1zM20 17h2v1h-2zM25 17h1v1h-1zM32 17h1v1h-1zM35 17h1v1h-1zM4 18h1v1h-1zM13 18h1v1h-1zM22 18h3v1h-3zM33 18h1v1h-1zM35 18h1v1h-1zM3 19h1v1h-1zM13 19h1v1h-1zM33 19h1v1h-1zM35 19h1v1h-1zM3 20h1v1h-1zM12 20h1v1h-1zM33 20h1v1h-1zM36 20h1v1h-1zM3 21h1v1h-1zM12 21h1v1h-1zM33 21h1v1h-1zM36 21h1v1h-1zM3 22h1v1h-1zM12 22h1v1h-1zM14 22h1v1h-1zM32 22h1v1h-1zM36 22h1v1h-1zM3 23h1v1h-1zM12 23h2v1h-2zM15 23h1v1h-1zM32 23h1v1h-1zM36 23h1v1h-1zM4 24h1v1h-1zM12 24h1v1h-1zM16 24h1v1h-1zM31 24h1v1h-1zM35 24h1v1h-1zM4 25h1v1h-1zM12 25h1v1h-1zM16 25h1v1h-1zM31 25h1v1h-1zM35 25h1v1h-1zM4 26h1v1h-1zM15 26h3v1h-3zM30 26h1v1h-1zM35 26h1v1h-1zM5 27h1v1h-1zM13 27h3v1h-3zM17 27h1v1h-1zM29 27h1v1h-1zM34 27h1v1h-1zM5 28h1v1h-1zM14 28h1v1h-1zM16 28h1v1h-1zM28 28h1v1h-1zM34 28h1v1h-1zM6 29h1v1h-1zM15 29h1v1h-1zM26 29h2v1h-2zM33 29h1v1h-1zM6 30h1v1h-1zM16 30h3v1h-3zM24 30h2v1h-2zM33 30h1v1h-1zM7 31h1v1h-1zM19 31h5v1h-5zM32 31h1v1h-1zM8 32h1v1h-1zM31 32h1v1h-1zM9 33h1v1h-1zM30 33h1v1h-1zM10 34h2v1h-2zM28 34h2v1h-2zM12 35h2v1h-2zM26 35h2v1h-2zM14 36h3v1h-3zM23 36h3v1h-3zM17 37h6v1h-6z",
        Tier.G to "M17 7h1v1h-1zM19 7h1v1h-1zM16 8h2v1h-2zM19 8h2v1h-2zM24 8h3v1h-3zM12 9h5v1h-5zM20 9h5v1h-5zM9 11h1v1h-1zM9 12h1v1h-1zM9 13h1v1h-1zM7 14h3v1h-3zM6 15h2v1h-2zM33 17h1v1h-1z",
        Tier.B to "M18 7h1v1h-1zM18 8h1v1h-1zM11 9h1v1h-1zM17 9h3v1h-3zM25 9h7v1h-7zM10 10h7v1h-7zM18 10h8v1h-8zM27 10h1v1h-1zM29 10h4v1h-4zM10 11h4v1h-4zM15 11h1v1h-1zM17 11h4v1h-4zM23 11h2v1h-2zM26 11h3v1h-3zM30 11h1v1h-1zM32 11h2v1h-2zM10 12h3v1h-3zM14 12h1v1h-1zM16 12h3v1h-3zM21 12h2v1h-2zM24 12h1v1h-1zM26 12h4v1h-4zM32 12h1v1h-1zM34 12h1v1h-1zM10 13h2v1h-2zM13 13h1v1h-1zM15 13h1v1h-1zM17 13h1v1h-1zM20 13h3v1h-3zM27 13h1v1h-1zM30 13h5v1h-5zM10 14h1v1h-1zM12 14h3v1h-3zM16 14h1v1h-1zM19 14h2v1h-2zM28 14h2v1h-2zM8 15h4v1h-4zM13 15h1v1h-1zM15 15h1v1h-1zM19 15h2v1h-2zM30 15h1v1h-1zM6 16h4v1h-4zM11 16h2v1h-2zM21 16h2v1h-2zM33 16h1v1h-1zM5 17h4v1h-4zM10 17h1v1h-1zM12 17h1v1h-1zM22 17h2v1h-2zM6 18h4v1h-4zM11 18h1v1h-1zM34 18h1v1h-1zM5 19h6v1h-6zM34 19h1v1h-1zM4 20h1v1h-1zM6 20h3v1h-3zM10 20h1v1h-1zM34 20h1v1h-1zM5 21h2v1h-2zM8 21h3v1h-3zM34 21h1v1h-1zM4 22h1v1h-1zM6 22h4v1h-4zM33 22h2v1h-2zM5 23h6v1h-6zM33 23h2v1h-2zM5 24h1v1h-1zM7 24h1v1h-1zM9 24h2v1h-2zM14 24h2v1h-2zM32 24h2v1h-2zM6 25h1v1h-1zM8 25h4v1h-4zM13 25h3v1h-3zM32 25h2v1h-2zM7 26h1v1h-1zM9 26h6v1h-6zM31 26h2v1h-2zM6 27h1v1h-1zM8 27h5v1h-5zM16 27h1v1h-1zM30 27h3v1h-3zM8 28h1v1h-1zM10 28h4v1h-4zM15 28h1v1h-1zM29 28h3v1h-3zM7 29h1v1h-1zM9 29h6v1h-6zM28 29h3v1h-3zM9 30h1v1h-1zM11 30h5v1h-5zM26 30h5v1h-5zM10 31h1v1h-1zM12 31h7v1h-7zM24 31h5v1h-5zM11 32h1v1h-1zM13 32h14v1h-14zM28 32h1v1h-1zM13 33h1v1h-1zM15 33h12v1h-12zM15 34h1v1h-1zM17 34h1v1h-1zM19 34h3v1h-3zM23 34h1v1h-1zM16 35h1v1h-1zM18 35h1v1h-1zM21 35h1v1h-1z",
        Tier.D to "M17 10h1v1h-1zM28 10h1v1h-1zM14 11h1v1h-1zM16 11h1v1h-1zM21 11h2v1h-2zM29 11h1v1h-1zM13 12h1v1h-1zM15 12h1v1h-1zM19 12h1v1h-1zM23 12h1v1h-1zM12 13h1v1h-1zM14 13h1v1h-1zM16 13h1v1h-1zM18 13h1v1h-1zM24 13h1v1h-1zM26 13h1v1h-1zM11 14h1v1h-1zM15 14h1v1h-1zM17 14h1v1h-1zM21 14h1v1h-1zM27 14h1v1h-1zM12 15h1v1h-1zM14 15h1v1h-1zM16 15h1v1h-1zM29 15h1v1h-1zM31 15h1v1h-1zM33 15h1v1h-1zM5 16h1v1h-1zM10 16h1v1h-1zM13 16h2v1h-2zM20 16h1v1h-1zM9 17h1v1h-1zM11 17h1v1h-1zM13 17h1v1h-1zM24 17h1v1h-1zM34 17h1v1h-1zM5 18h1v1h-1zM10 18h1v1h-1zM12 18h1v1h-1zM4 19h1v1h-1zM11 19h2v1h-2zM5 20h1v1h-1zM9 20h1v1h-1zM11 20h1v1h-1zM35 20h1v1h-1zM4 21h1v1h-1zM7 21h1v1h-1zM11 21h1v1h-1zM35 21h1v1h-1zM5 22h1v1h-1zM10 22h2v1h-2zM35 22h1v1h-1zM4 23h1v1h-1zM11 23h1v1h-1zM14 23h1v1h-1zM35 23h1v1h-1zM6 24h1v1h-1zM8 24h1v1h-1zM11 24h1v1h-1zM13 24h1v1h-1zM34 24h1v1h-1zM5 25h1v1h-1zM7 25h1v1h-1zM34 25h1v1h-1zM5 26h2v1h-2zM8 26h1v1h-1zM33 26h2v1h-2zM7 27h1v1h-1zM33 27h1v1h-1zM6 28h2v1h-2zM9 28h1v1h-1zM32 28h2v1h-2zM8 29h1v1h-1zM31 29h2v1h-2zM7 30h2v1h-2zM10 30h1v1h-1zM31 30h2v1h-2zM8 31h2v1h-2zM11 31h1v1h-1zM29 31h3v1h-3zM9 32h2v1h-2zM12 32h1v1h-1zM27 32h1v1h-1zM29 32h2v1h-2zM10 33h3v1h-3zM14 33h1v1h-1zM27 33h3v1h-3zM12 34h3v1h-3zM16 34h1v1h-1zM18 34h1v1h-1zM22 34h1v1h-1zM24 34h4v1h-4zM14 35h2v1h-2zM17 35h1v1h-1zM19 35h2v1h-2zM22 35h4v1h-4zM17 36h6v1h-6z",
        Tier.F1 to "M35 16h1v1h-1zM32 18h1v1h-1zM36 18h1v1h-1zM32 19h1v1h-1zM36 19h1v1h-1z",
    )

    /** The four flames, each lifting on its own clock. */
    val flames: List<List<Pair<Tier, String>>> = listOf(
        listOf(
            Tier.F1 to "M7 6h1v1h-1zM6 7h1v1h-1zM5 8h1v1h-1zM7 8h1v1h-1zM5 9h1v1h-1zM5 10h1v1h-1zM8 10h1v1h-1zM4 11h1v1h-1zM8 11h1v1h-1zM5 12h1v1h-1zM5 13h1v1h-1zM8 13h1v1h-1zM6 14h1v1h-1z",
            Tier.F2 to "M6 8h1v1h-1zM6 9h2v1h-2zM6 10h2v1h-2zM5 11h1v1h-1zM7 11h1v1h-1zM8 12h1v1h-1zM6 13h1v1h-1z",
            Tier.F3 to "M6 11h1v1h-1zM6 12h2v1h-2zM7 13h1v1h-1z",
        ),
        listOf(
            Tier.F1 to "M13 2h1v1h-1zM14 3h1v1h-1zM13 4h1v1h-1zM15 4h1v1h-1zM13 5h1v1h-1zM15 5h1v1h-1zM12 6h1v1h-1zM16 6h1v1h-1zM12 7h1v1h-1zM16 7h1v1h-1zM13 8h1v1h-1zM15 8h1v1h-1z",
            Tier.F2 to "M14 4h1v1h-1zM14 5h1v1h-1zM13 6h1v1h-1zM15 6h1v1h-1zM15 7h1v1h-1z",
            Tier.F3 to "M14 6h1v1h-1zM13 7h2v1h-2zM14 8h1v1h-1z",
        ),
        listOf(
            Tier.F1 to "M21 2h1v1h-1zM22 3h1v1h-1zM23 4h1v1h-1zM20 5h1v1h-1zM23 5h1v1h-1zM20 6h1v1h-1zM24 6h1v1h-1zM20 7h1v1h-1zM24 7h1v1h-1zM21 8h1v1h-1zM23 8h1v1h-1z",
            Tier.F2 to "M21 3h1v1h-1zM21 4h2v1h-2zM21 5h2v1h-2zM21 6h1v1h-1zM23 6h1v1h-1zM23 7h1v1h-1z",
            Tier.F3 to "M22 6h1v1h-1zM21 7h2v1h-2zM22 8h1v1h-1z",
        ),
        listOf(
            Tier.F1 to "M27 2h1v1h-1zM28 3h1v1h-1zM29 4h1v1h-1zM26 5h1v1h-1zM29 5h1v1h-1zM26 6h1v1h-1zM30 6h1v1h-1zM30 7h1v1h-1z",
            Tier.F2 to "M27 3h1v1h-1zM27 4h2v1h-2zM27 5h2v1h-2zM27 6h1v1h-1zM29 6h1v1h-1zM29 7h1v1h-1z",
            Tier.F3 to "M28 6h1v1h-1zM27 7h2v1h-2z",
        ),
    )
}
