package io.github.frenchiiifries.emb3r.ui

// Generated by android/tools/mark_to_kotlin.py from #logo in src/index.html.
// Do not edit by hand - change the desktop's wordmark and regenerate.

object Wordmark {
    /** The rows, exactly as the desktop's <pre> holds them. */
    val rows: List<String> = listOf(
        "███████╗███╗   ███╗██████╗ ██████╗ ██████╗",
        "██╔════╝████╗ ████║██╔══██╗╚════██╗██╔══██╗",
        "█████╗  ██╔████╔██║██████╔╝ █████╔╝██████╔╝",
        "██╔══╝  ██║╚██╔╝██║██╔══██╗ ╚═══██╗██╔══██╗",
        "███████╗██║ ╚═╝ ██║██████╔╝██████╔╝██║  ██║",
        "╚══════╝╚═╝     ╚═╝╚═════╝ ╚═════╝ ╚═╝  ╚═╝",
    )

    /** Columns in the widest row, for fitting it to the screen. */
    const val COLUMNS = 43
}
