"""Generates CoilMarkData.kt from the salamander in src/index.html.

The phone draws the same mark as the desktop, from the same path data. Copying
6,000 characters of coordinates by hand is how a mark ends up almost the same,
so it is generated instead - rerun this if the desktop's mark ever changes:

    python android/tools/mark_to_kotlin.py
"""
import io
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
HTML = os.path.join(ROOT, "src", "index.html")
OUT = os.path.join(ROOT, "android", "app", "src", "main", "java", "io", "github",
                   "frenchiiifries", "emb3r", "ui", "CoilMarkData.kt")

html = io.open(HTML, encoding="utf-8").read()
start = html.index('<svg id="logoMark"')
svg = html[start:html.index("</svg>", start) + len("</svg>")]

viewbox = re.search(r'viewBox="([^"]+)"', svg).group(1)
assert viewbox == "0 0 40 40", "the mark's canvas changed: " + viewbox

static, flames, current = [], [], None
for m in re.finditer(r"<(/?)(g|path)([^>]*?)/?>", svg):
    closing, tag, attrs = m.groups()
    if tag == "g":
        if closing:
            current = None
        else:
            current = []
            flames.append(current)
        continue
    if closing:
        continue
    tier = re.search(r'class="([^"]+)"', attrs).group(1)
    d = re.search(r' d="([^"]+)"', attrs).group(1)
    (current if current is not None else static).append((tier.upper(), d))

assert len(flames) == 4, "expected four flame groups, found %d" % len(flames)


def kt(pairs, indent):
    return (",\n" + indent).join('Tier.%s to "%s"' % (t, d) for t, d in pairs)


body = '''package io.github.frenchiiifries.emb3r.ui

// Generated by android/tools/mark_to_kotlin.py from #logoMark in src/index.html.
// Do not edit by hand - change the desktop's mark and regenerate.

/** The seven tiers of the salamander, each a mix of the accent colour. */
enum class Tier { O, D, B, G, F1, F2, F3 }

object CoilMarkData {
    /** The canvas the paths are drawn on, in the SVG's own units. */
    const val VIEWBOX = 40f

    /** The body and the flame bases, which do not move. */
    val static: List<Pair<Tier, String>> = listOf(
        %s,
    )

    /** The four flames, each lifting on its own clock. */
    val flames: List<List<Pair<Tier, String>>> = listOf(
%s
    )
}
''' % (kt(static, "        "),
       "\n".join("        listOf(\n            %s,\n        )," % kt(g, "            ") for g in flames))

io.open(OUT, "w", encoding="utf-8", newline="\n").write(body)
print("wrote %s: %d static paths, %d flames (%s)" % (
    os.path.relpath(OUT, ROOT), len(static), len(flames), ", ".join(str(len(g)) for g in flames)))
