"""Generates CoilMarkData.kt and Wordmark.kt from the desktop's src/index.html.

The phone draws the same salamander and the same EMB3R wordmark as the desktop,
from the same source. Copying 6,000 characters of coordinates, or six rows of
box-drawing characters, by hand is how a mark ends up almost the same - so both
are generated instead. Rerun this if either ever changes on the desktop:

    python android/tools/mark_to_kotlin.py
"""
import io
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
HTML = os.path.join(ROOT, "src", "index.html")
UI = os.path.join(ROOT, "android", "app", "src", "main", "java", "io", "github",
                  "frenchiiifries", "emb3r", "ui")
NL = "\n"

html = io.open(HTML, encoding="utf-8").read()


def write(name, text):
    path = os.path.join(UI, name)
    io.open(path, "w", encoding="utf-8", newline=NL).write(text)
    return os.path.relpath(path, ROOT)


# ---- the salamander: #logoMark ----
start = html.index('<svg id="logoMark"')
svg = html[start:html.index("</svg>", start) + len("</svg>")]

viewbox = re.search(r'viewBox="([^"]+)"', svg).group(1)
assert viewbox == "0 0 40 40", "the mark's canvas changed: " + viewbox

static, flames, current = [], [], None
for m in re.finditer(r"<(/?)(g|path)([^>]*?)/?>", svg):
    closing, tag, attrs = m.groups()
    if tag == "g":
        if closing:
            current = None
        else:
            current = []
            flames.append(current)
        continue
    if closing:
        continue
    tier = re.search(r'class="([^"]+)"', attrs).group(1)
    d = re.search(r' d="([^"]+)"', attrs).group(1)
    (current if current is not None else static).append((tier.upper(), d))

assert len(flames) == 4, "expected four flame groups, found %d" % len(flames)


def kt(pairs, indent):
    return ("," + NL + indent).join('Tier.%s to "%s"' % (t, d) for t, d in pairs)


flame_blocks = NL.join(
    "        listOf(" + NL + "            " + kt(g, "            ") + "," + NL + "        ),"
    for g in flames
)

mark = NL.join([
    "package io.github.frenchiiifries.emb3r.ui",
    "",
    "// Generated by android/tools/mark_to_kotlin.py from #logoMark in src/index.html.",
    "// Do not edit by hand - change the desktop's mark and regenerate.",
    "",
    "/** The seven tiers of the salamander, each a mix of the accent colour. */",
    "enum class Tier { O, D, B, G, F1, F2, F3 }",
    "",
    "object CoilMarkData {",
    "    /** The canvas the paths are drawn on, in the SVG's own units. */",
    "    const val VIEWBOX = 40f",
    "",
    "    /** The body and the flame bases, which do not move. */",
    "    val static: List<Pair<Tier, String>> = listOf(",
    "        " + kt(static, "        ") + ",",
    "    )",
    "",
    "    /** The four flames, each lifting on its own clock. */",
    "    val flames: List<List<Pair<Tier, String>>> = listOf(",
    flame_blocks,
    "    )",
    "}",
    "",
])
print("wrote %s: %d static paths, %d flames (%s)" % (
    write("CoilMarkData.kt", mark), len(static), len(flames), ", ".join(str(len(g)) for g in flames)))


# ---- the EMB3R wordmark: six rows of box-drawing characters in <pre id="logo"> ----
w_start = html.index('<pre id="logo">') + len('<pre id="logo">')
raw = html[w_start:html.index("</pre>", w_start)]
rows = [r.rstrip() for r in raw.strip(NL).split(NL)]
assert len(rows) == 6, "expected six rows in the wordmark, found %d" % len(rows)
columns = max(len(r) for r in rows)

wordmark = NL.join([
    "package io.github.frenchiiifries.emb3r.ui",
    "",
    "// Generated by android/tools/mark_to_kotlin.py from #logo in src/index.html.",
    "// Do not edit by hand - change the desktop's wordmark and regenerate.",
    "",
    "object Wordmark {",
    "    /** The rows, exactly as the desktop's <pre> holds them. */",
    "    val rows: List<String> = listOf(",
    NL.join('        "%s",' % r for r in rows),
    "    )",
    "",
    "    /** Columns in the widest row, for fitting it to the screen. */",
    "    const val COLUMNS = %d" % columns,
    "}",
    "",
])
print("wrote %s: %d rows, %d columns" % (write("Wordmark.kt", wordmark), len(rows), columns))
